import Hyundai_i20 from "./assets/Hyundai_i20.webp";
import Toyota_Yaris_1A from "./assets/Toyota_Yaris_1A.webp";

// اطلاعات متغیر ماشین‌ها در این فایل ذخیره می‌شود
export const allCars = [
  {
    id: 1,
    name: "Toyota",
    model: "Yaris 1A",
    price: 350,
    img: Toyota_Yaris_1A,
    category: "Standard",
    horsepower: 106,
    engine: "1.5L 4-Cylinder",
    transmission: "CVT Automatic",
    fuel: "Gasoline",
  },
  {
    id: 2,
    name: "Honda",
    model: "Civic",
    price: 320,
    img: Toyota_Yaris_1A,
    category: "Standard",
    horsepower: 158,
    engine: "2.0L 4-Cylinder",
    transmission: "CVT Automatic",
    fuel: "Gasoline",
  },
  {
    id: 3,
    name: "Hyundai",
    model: "i20",
    price: 250,
    img: Hyundai_i20,
    category: "Prestige",
    horsepower: 120,
    engine: "1.0L Turbo",
    transmission: "7-Speed DCT",
    fuel: "Gasoline",
  },
  {
    id: 4,
    name: "BMW",
    model: "3 Series",
    price: 450,
    img: Hyundai_i20,
    category: "Prestige",
    horsepower: 255,
    engine: "2.0L TwinPower Turbo",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
  },
  {
    id: 5,
    name: "Toyota",
    model: "RAV4",
    price: 400,
    img: Toyota_Yaris_1A,
    category: "SUV",
    horsepower: 203,
    engine: "2.5L 4-Cylinder",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
  },
  {
    id: 6,
    name: "Hyundai",
    model: "Tucson",
    price: 380,
    img: Hyundai_i20,
    category: "SUV",
    horsepower: 187,
    engine: "2.5L 4-Cylinder",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
  },
  {
    id: 7,
    name: "Toyota",
    model: "Corolla",
    price: 280,
    img: Toyota_Yaris_1A,
    category: "Economy",
    horsepower: 139,
    engine: "1.8L 4-Cylinder",
    transmission: "CVT Automatic",
    fuel: "Gasoline",
  },
  {
    id: 8,
    name: "Mercedes-Benz",
    model: "E-Class",
    price: 550,
    img: Hyundai_i20,
    category: "Luxury",
    horsepower: 255,
    engine: "2.0L Turbo",
    transmission: "9-Speed Automatic",
    fuel: "Gasoline",
  },
  {
    id: 9,
    name: "Tesla",
    model: "Model 3",
    price: 520,
    img: Hyundai_i20,
    category: "Electric",
    horsepower: 283,
    engine: "Electric Motor",
    transmission: "Single Speed",
    fuel: "Electric",
  },
  {
    id: 10,
    name: "BMW",
    model: "i4",
    price: 480,
    img: Toyota_Yaris_1A,
    category: "Electric",
    horsepower: 335,
    engine: "Dual Electric Motors",
    transmission: "Single Speed",
    fuel: "Electric",
  },
  {
    id: 11,
    name: "Porsche",
    model: "911",
    price: 600,
    img: Hyundai_i20,
    category: "Sports",
    horsepower: 379,
    engine: "3.0L Twin-Turbo",
    transmission: "8-Speed PDK",
    fuel: "Gasoline",
  },
  // --- ماشین جدید با موجودی صفر ---
  {
    id: 12,
    name: "Nissan",
    model: "Altima",
    price: 310,
    img: Toyota_Yaris_1A,
    category: "Standard",
    horsepower: 188,
    engine: "2.5L 4-Cylinder",
    transmission: "CVT Automatic",
    fuel: "Gasoline",
    inStock: false, // این کلید باعث می‌شود موجود نباشد
  },
];
